#!/usr/bin/env python3

import sys
import math
import __future__


SUB_INT = 10000
B_VAL = 5000
INTEGRAL_VAL = math.pi / 2


def Description():
    print("USAGE")
    print("\t./110borwein n\n")
    print("DESCRIPTION")
    print("\tn\tconstant defining the integral to be computed\n")


def Error_handle():
    if len(sys.argv) != 2:
        raise Exception("Bad number of arguments")

    if sys.argv[1] == '-h':
        Description()
        sys.exit(0)

    try:
        n = int(sys.argv[1])
    except ValueError:
        raise Exception("Bad argument")

    if n < 0:
        raise Exception("The n number can't be negative")

    return n


def formula(n, x):
    if not x:
        return 1
    formule = math.sin(x) / x
    i = 0.5
    while i <= n:
        formule *= (math.sin(x / (2 * i + 1)) / (x / (2 * i + 1)))
        i += 0.5
    return formule


def midpoint(n):
    print("Midpoint:")
    width = B_VAL / SUB_INT
    sumed = 0
    i = 0.5
    while i <= B_VAL:
        sumed += formula(n, (((i - 0.5) + i) / 2)) * width
        i += 0.5
    diff = abs(INTEGRAL_VAL - sumed)
    print("IO = %.10f\ndiff = %.10f\n" % (sumed, diff))
    return


def trapezoids(n):
    print("Trapezoidal:")
    width = B_VAL / SUB_INT
    sumed = (width / 2) * formula(n, 0)
    i = 0.5
    while i <= B_VAL - 0.5:
        sumed += (width / 2) * formula(n, i) * 2
        i += 0.5
    sumed += (width / 2) * formula(n, B_VAL)
    diff = abs(INTEGRAL_VAL - sumed)
    print("IO = %.10f\ndiff = %.10f\n" % (sumed, diff))
    return


def simpson(n):
    print("Simpson:")
    width = B_VAL / SUB_INT
    sumed = (width / 3) * formula(n, 0)
    for counter in range(1, SUB_INT):
        sumed += (width / 3) * (formula(n, counter * width) * (4 if counter % 2 == 1 else 2))
    sumed += (width / 3) * formula(n, B_VAL)
    diff = abs(INTEGRAL_VAL - sumed)
    print("IO = %.10f\ndiff = %.10f" % (sumed, diff))
    return


def main():
    n = Error_handle()
    midpoint(n)
    trapezoids(n)
    simpson(n)


if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print(e)
        sys.exit(84)